name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.34.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: patch

      - name: Update version.md
        run: echo "v$(echo $(git describe --tags $(git rev-list --tags --max-count=1)))" > version.md

      - name: Commit and push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m "Bump version number" -a
          git push

#      - name: Set up JDK 21
#        uses: actions/setup-java@v2
#        with:
#          java-version: '21'
#          distribution: 'adopt'

#      - name: Grant execute permission for gradlew
#        run: chmod +x gradlew
#
#      - name: Build with Gradle
#        run: ./gradlew build
#
#      - name: Test with Gradle
#        run: ./gradlew test

#      - name: Run OWASP Dependency Check
#        uses: jeremylong/DependencyCheck@v6
#        with:
#          format: 'ALL'
#          failBuildOnCVSS: '7'
#          suppressionFile: 'suppressions.xml'
#
#      - name: SonarCloud Scan
#        uses: sonarsource/sonarcloud-github-action@master
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
#          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}